/** Default expense/income categories matching the original RICH app order. */
export const DEFAULT_CATEGORIES: Array<{ name: string; icon: string }> = [
  { name: '餐饮', icon: 'food' },
  { name: '衣服', icon: 'tshirt' },
  { name: '交通', icon: 'bus' },
  { name: '网费话费', icon: 'phone' },
  { name: '学习', icon: 'book' },
  { name: '日用', icon: 'jug' },
  { name: '住房', icon: 'house' },
  { name: '医疗', icon: 'medkit' },
  { name: '发红包', icon: 'redpacket' },
  { name: '汽车/加油', icon: 'fuel' },
  { name: '娱乐', icon: 'gamepad' },
  { name: '请客送礼', icon: 'gift' },
  { name: '电器数码', icon: 'camera' },
  { name: '运动', icon: 'dumbbell' },
  { name: '理发', icon: 'scissors' },
  { name: '付费会员', icon: 'gem' },
  { name: '还钱', icon: 'coins' },
  { name: '工作', icon: 'briefcase' },
  { name: '购物', icon: 'bag' },
  { name: '旅行', icon: 'suitcase' },
  { name: '人情/借钱', icon: 'handshake' },
  { name: '买菜', icon: 'carrot' },
];
