/**
 * Semantic icon fallbacks for built-in categories and common subcategories.
 * Stored icon ids still win; these names keep imports and child categories
 * visually useful even when they do not have an explicit icon column.
 */
const CATEGORY_ICON_BY_NAME: Record<string, string> = {
  餐饮: 'food',
  校园餐饮: 'bowl',
  早餐: 'bread',
  午餐: 'noodles',
  晚餐: 'drumstick',
  三餐: 'bowl',
  宵夜: 'pizza',
  聚餐: 'party',
  外卖: 'burger',
  零食: 'snack',
  水果: 'apple',
  饮料: 'drink',
  咖啡: 'coffee',
  买菜: 'carrot',
  柴米油盐: 'bottles',

  衣服: 'tshirt',
  美妆: 'lipstick',
  购物: 'bag',
  饰品: 'necklace',
  鞋子: 'shoe',

  交通: 'bus',
  公交: 'bus',
  公交地铁: 'metro',
  地铁: 'metro',
  打车: 'taxi',
  自行车: 'bike',
  飞机: 'plane',
  火车: 'train',
  轮船: 'ship',
  汽车: 'car',
  汽车加油: 'fuel',
  '汽车/加油': 'fuel',
  油费: 'fuel',
  停车: 'parkpin',
  停车费: 'parkpin',
  过路费: 'toll',
  洗车: 'carwash',
  维修保养: 'wrench',

  网费话费: 'phone',
  网络通讯: 'signal',
  手机: 'phone',
  软件: 'appstore',
  效率工具: 'laptop',
  电子产品: 'laptop',
  电器数码: 'camera',
  电器: 'washer',
  相机: 'camera',
  '3c配件': 'cable',
  购买app: 'appstore',
  付费会员: 'gem',
  视频: 'film',
  音乐: 'mic',
  云存储: 'signal',
  k歌: 'mic',
  打赏: 'handcoin',

  学习: 'book',
  学费: 'grad',
  书籍: 'book',
  文具: 'ruler',
  考试: 'exam',
  培训: 'grad',

  日用: 'jug',
  清洁: 'broom',
  理发: 'scissors',
  洗澡: 'bathtub',
  快递: 'box',
  家具: 'sofa',
  水电煤: 'drop',
  水电网: 'drop',

  住房: 'house',
  房租: 'houseyen',
  房贷: 'houseloan',
  住宿: 'hotel',
  酒店: 'hotel',
  酒店住宿: 'hotel',

  医疗: 'medkit',
  看诊: 'heartpulse',
  挂号费: 'regbox',
  就诊: 'clipplus',
  药品: 'pill',
  住院: 'hospbed',
  保健品: 'heartpulse',
  健身: 'dumbbell',
  运动: 'dumbbell',

  发红包: 'redpacket',
  收红包: 'redpacket',
  请客送礼: 'gift',
  礼金: 'envmoney',
  人情: 'handshake',
  '人情/借钱': 'handshake',
  还钱: 'coins',
  恋爱: 'love',
  家人: 'family',
  父母: 'parent',
  孩子: 'baby',
  宠物: 'paw',
  育儿: 'baby',
  奶粉: 'milkcan',
  奶瓶: 'babybottle',
  辅食: 'babyfood',
  纸尿裤: 'diaper',
  玩具: 'pinwheel',
  早教: 'bulb',
  亲子游: 'parentchild',
  疫苗看病: 'syringe',

  娱乐: 'gamepad',
  游戏: 'gamepad',
  聚会: 'party',
  电影: 'film',
  活动门票: 'ticket',
  景区门票: 'ticket',
  旅行: 'suitcase',
  宴请招待: 'bell',
  差旅费: 'ticketyen',

  工作: 'briefcase',
  工资: 'wallet',
  工资薪水: 'wallet',
  员工工资: 'wallet',
  生活费: 'moneybag',
  兼职: 'clockyen',
  兼职外快: 'clockyen',
  理财: 'chart',
  投资理财: 'chart',
  奖金: 'briefcaseyen',
  员工奖金: 'trophyyen',
  水电杂费: 'drop',
  办公用品: 'printer',
  场地租金: 'buildingyen',
  进货费: 'cartbox',
  维修费: 'wrench',
  清洁费: 'broom',
  材料费: 'boxstack',
  物流费: 'truck',
  员工团建: 'flag',
  报销: 'ticketyen',
  退款: 'refund',
  退款返款: 'refund',
  保险: 'umbrella',
  捐赠: 'handheart',
  利息: 'coins',
  其他收入: 'piggy',
  其他收益: 'piggy',

  烟酒: 'wine',
  汽车罚款: 'minuscircle',
  车贷: 'caryen',
  配件: 'steering',
  车险: 'carshield',
  车检: 'carsearch',
  管理分类: 'gear',
  其他: 'grid',
};

export function iconIdForCategory(name?: string | null): string {
  const normalizedName = name?.trim();
  return (normalizedName && CATEGORY_ICON_BY_NAME[normalizedName]) || 'grid';
}
